### ISSUE TITLE
File not found, after the file was renamed

### ISSUE THREAD

**Issue by Walterium** [R0Wi-DEV/workflow_ocr#112] opened 2022-04-13 14:57 UTC
Hi, first of all thank you very much for the app. It helps me a lot!
I setup the workflow to do OCR on new created PDF files.
The background-jobs are executed by cron every 5 minutes.
However when I upload a new PDF file and quickly rename it, before the next cron-job was executed, then the file isn't found during the next workflow execution. Please find below the error message I get in the Nextcloud log.

`[workflow_ocr] Warnung: Could not process file '/Nicolas/files/Dokumente/2021-04-15 Philips 346B Curved Bildschirm_test.pdf'. File was not found`

The following work flow executions then probably doesn't treat the file as new anymore and so the file is never been processed.

Please let me know, if I can be of any assistance to provide further details about this issue.

**Comment by R0Wi** [comment] 2022-04-13 20:13
Hi @Walterium thanks fir your kind words and thank you for reporting this.

To quickly overcome this issue you could imagine adding the "file updated" trigger to your workflow like described [here](https://github.com/R0Wi/workflow_ocr#trigger-ocr-if-file-was-created-or-updated).

Nevertheless i'll have a closer look at this issue and give you some feedback about it. Please be patient since there are a few issues i have to look at, first.

**Comment by R0Wi** [comment] 2022-05-30 21:38
Ok i think i can reproduce this issue. The fix would be to attach a handler for the "file-changd" event and handle it in a way of checking if that files is queued for OCR processing. If that's the case we should adjust the file path to the renamed file inside the job-queue accordingly.

**Comment by Walterium** [comment] 2022-05-31 20:07
Hi R0Wi, thank you for looking into this. That sounds like a good solution.
I just checked, that this issue also occurs with "file updated" and "file renamed" trigger added to the workflow.
So it would really help me, when it's solved.

**Comment by barrex-git** [comment] 2022-10-17 22:50
Good evening,
the problem also exists when uploading a file via the GUI or API and moving it to another directory before the cronjob has been executed. As soon as the file is uploaded, the following tag is generated in the oc_jobs:

`| OCA\WorkflowOcr\BackgroundJobs\ProcessFileJob                   | {"filePath":"\/dev\/files\/WiPl_2021.pdf","settings":"{\"languages\":[\"deu\",\"eng\"],\"tagsToAddAfterOcr\":[2]}"}`

This tag is not updated in the oc_jobs when you move the file. As soon as the cronjob is executed, it tries to read the file at the old path - the log generates the error message: File could not be found.

I have tried a few options, but unfortunately nothing leads to success. The only thing that worked for me was to copy the file and not to move. This makes it all a bit messy because you have to delete the original files after copying and a lot of users don't understand the difference between copy and move, which leads to user errors. Here are the settings for copy:

![options](https://user-images.githubusercontent.com/116026278/196292897-80dffb9a-442f-4c11-a97c-2367b860c492.png)


It would be the best to add a "move" item to the "When..." options. In the meantime, is there any news about the issue or does anyone have a solution?

Furthermore, I noticed that tags set by the app "Automated tagging" cannot be removed by the "Remove tags after OCR" option. Can you be more specific about that?

Best thanks by the way for the great work....

Greetings, barrex

**Comment by R0Wi** [comment] 2022-10-18 04:33
Hi @barrex-git, I think you described the problem when moving a file before it was grabbed by the cronjob quite well. Like I mentioned, the (programatic) fix would be to listen to file renamed events and modify existing cron job entries accordingly. Sadly I didn't find the time to implement this, yet.

> It would be the best to add a "move" item to the "When..." options. In the meantime, is there any news about the issue or does anyone have a solution?

Unfortunately the app cannot define "triggers" itself since this is a basic function of the Nextcloud workflow engine. I didn't have the time to check it yet, but you could try to add the "File renamed" trigger. This should readd the file to the cronjob queue as soon as it was renamed. It won't remove the old entry so you will still notice that some jobs might fail but in theory the job which was triggerd by the rename operation should succeed.

> Furthermore, I noticed that tags set by the app "Automated tagging" cannot be removed by the "Remove tags after OCR" option. Can you be more specific about that?

It would be best if you open a new issue for that. The feature was developed in https://github.com/R0Wi/workflow_ocr/issues/88 and it should work if you try to remove a tag which was added by "Automated tagging" after the OCR process finished. If not I think we need further information like log files etc 👍

**Comment by R0Wi** [comment] 2022-10-18 04:42
Did a quick check and saw that adding the "File renamed" event does not seem to readd the file. Seems like there is currently no workaround then except running the cron job before moving the file 😢

**Comment by barrex-git** [comment] 2022-10-18 10:30
Hello @R0Wi,
thank you very much for your quick reply.

I've dealt with the issue again this morning and checked the code of both apps "Automated tagging" & "OCR Workflow".
After several tries I have found a solution for the issue - this configuration allows files to be **moved, renamed or copied** directly after uploading via GUI/API and the OCR-Workflow-Process will be triggered at the next cronjob with the new, correct filename/path. Of course, attached processes such as "Elasticsearch - Indexing" are also executed afterwards. 

The only problem is that the old path is not removed from the oc_jobs and therefore a warning "File not found" is written for the old file to the log - if this disturbs, you can still adjust the log process.

oc_jobs after file upload:
![uploaded-file](https://user-images.githubusercontent.com/116026278/196400315-5d667428-9979-4d46-98e2-12eaaf0e86d8.png)

oc_jobs after file moving:
![moved-file](https://user-images.githubusercontent.com/116026278/196402590-0d4370dc-0e02-49c5-8bf3-e70fe3aea37a.png)

Regarding the remove tag issue: I forgot a condition, so the tag was not removed properly.

Workaround: (a bit complex, but functional) 

![move-WORK-2](https://user-images.githubusercontent.com/116026278/196404360-3ca4330f-13fa-4d41-ab5f-1ce2123c71a8.png)

Greetings,
barrex

**Comment by weltmaister** [comment] 2023-05-09 10:10
First of all: BIG THANKS for the work!
And a question: all file related procedere in nextcloud seems to be stick to the unique file id every folder and file gets internally. wouldnt it a better solution to work with this id rather than with the (possibly changing) file path?

**Comment by R0Wi** [comment] 2023-05-09 11:22
Initially the app worked with the file id but I had problems when trying to setup the user environment before processing the file asynchronously. But yeah, good hint, might re-evaluate the approach.

**Closed** 2023-08-27 19:53 UTC
Labels: bug, pinned

**Comment by R0Wi** [comment] 2023-09-08 15:49
Fix included in `v1.27.2` :rocket:

**Comment by Rednox** [comment] 2023-10-08 19:12
@R0Wi unfortunately I still have the renaming issue with version 1.27.5 with NC27. Can I somehow fix it?

**Comment by R0Wi** [comment] 2023-10-09 06:01
@Rednox I cannot reproduce the problem. Here is what I did on a fresh NC installation:

1. Pause the NC cron
2. Configure the workflow to run on "file created" and "MIME type is PDF"
3. Upload a new `pdf` file
4. Rename the file immediately after the upload
5. Run the cron manually via `php cron.php`

Result: the file still gets picked up and is processed correctly. So the debug logs look like this:

![image](https://github.com/R0Wi-DEV/workflow_ocr/assets/19730957/f390a872-0a44-40bc-82c1-74c6f95e8ca7)

Any additional logs in your case?

**Comment by Rednox** [comment] 2023-10-10 13:05
@R0Wi I can't show you logs for the error because I don't actually get any representative logs because of this flooding statements in my logs

<img width="976" alt="image" src="https://github.com/R0Wi-DEV/workflow_ocr/assets/2861965/78f548c5-94e3-490e-83b9-13529a9080f5">

So the issue seems only to exist with my setup to have a automated tagging flow and an OCR flow. 
After some tests I identified that the flow is not working, if I check on the automated tag "ocr_todo" in the ocr flow because it somehow is not there yet.

<img width="911" alt="image" src="https://github.com/R0Wi-DEV/workflow_ocr/assets/2861965/646673f3-3c46-4b08-87f4-dd4e047267e4">

**Comment by R0Wi** [comment] 2023-10-13 16:06
@Rednox I didn't yet fully understand your issue but it seems to be a different one. Maybe it would make sense if you drop me a private message via email and the two of us will try to figure out what's going on first. Please feel free to contact me :+1:
